spring.application.name=huza-backend

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/huza}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:huza}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:change-me}


spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_USERNAME}
spring.mail.password=${GMAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

app.verification.token.expiration=3600000