
# SPRING APPLICATION

spring.application.name=huza-backend

# DATABASE

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/huza}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:kevine@123}
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# EMAIL

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME:kevineumukundwa0@gmail.com}
spring.mail.password=${EMAIL_PASSWORD:kevine@12345}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true


# JWT CONFIGURATION

security.jwt.secret-key=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
security.jwt.expiration-time=3600000

# SWAGGER

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.packages-to-scan=com.huza.huzabackend.controller

# VERIFICATION TOKEN

app.verification.token.expiration=3600000

# FRONTEND URL

app.frontend.url=${FRONTEND_URL:http://localhost:3000}


spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email